# -*- coding: utf-8 -*-
"""ROCK VS MINE PREDICTION.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H0XpFbF3Bml99ExXTDriYq3MSKxOLWaJ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

sonar_data=pd.read_csv('/Copy of sonar data.csv',header=None)
sonar_data.head()

sonar_data.describe()

sonar_data[60].value_counts()

sonar_data.groupby(60).mean()

X=sonar_data.drop(columns=60,axis=1)
Y=sonar_data[60]

print(X)
print(Y)

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1,stratify=Y,random_state=1)

print(X.shape,X_test.shape,X_train.shape)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train,Y_train)

from sklearn.metrics import accuracy_score
X_trainprediction=model.predict(X_train)
train_accuracy=accuracy_score(X_trainprediction,Y_train)

print(train_accuracy)

X_testprediction=model.predict(X_test)
test_accuracy=accuracy_score(X_testprediction,Y_test)

print(test_accuracy)

input_data=(0.0323,0.0101,0.0298,0.0564,0.0760,0.0958,0.0990,0.1018,0.1030,0.2154,0.3085,0.3425,0.2990,0.1402,0.1235,0.1534,0.1901,0.2429,0.2120,0.2395,0.3272,0.5949,0.8302,0.9045,0.9888,0.9912,0.9448,1.0000,0.9092,0.7412,0.7691,0.7117,0.5304,0.2131,0.0928,0.1297,0.1159,0.1226,0.1768,0.0345,0.1562,0.0824,0.1149,0.1694,0.0954,0.0080,0.0790,0.1255,0.0647,0.0179,0.0051,0.0061,0.0093,0.0135,0.0063,0.0063,0.0034,0.0032,0.0062,0.0067)
input_dataasnumpy=np.asarray(input_data)

input_datareshape=input_dataasnumpy.reshape(1,-1)
prediction=model.predict(input_datareshape)


if(prediction[0]=='R'):
  print("The object is Rock")
else:
  print("The object is mine")